const ACTIONS = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',

    CLIENTS_LOAD_ALL: 'CLIENTS_LOAD_ALL',
    CLIENTS_LOAD_ALL_SUCCESS: 'CLIENTS_LOAD_ALL_SUCCESS',
    CLIENTS_LOAD_ALL_FAILED: 'CLIENTS_LOAD_ALL_FAILED',

    CLIENT_LOAD_ANSWERS: 'CLIENT_LOAD_ANSWERS',
    CLIENT_LOAD_ANSWERS_SUCCESS: 'CLIENT_LOAD_ANSWERS_SUCCESS',
    CLIENT_LOAD_ANSWERS_FAILED: 'CLIENT_LOAD_ANSWERS_FAILED',

    CLIENT_LOAD_THOUGHTS: 'CLIENT_LOAD_THOUGHTS',
    CLIENT_LOAD_THOUGHTS_SUCCESS: 'CLIENT_LOAD_THOUGHTS_SUCCESS',
    CLIENT_LOAD_THOUGHTS_FAILED: 'CLIENT_LOAD_THOUGHTS_FAILED',

    CLIENT_LOAD_NOTES_ABOUT: 'CLIENT_LOAD_NOTES_ABOUT',
    CLIENT_LOAD_NOTES_ABOUT_SUCCESS: 'CLIENT_LOAD_NOTES_ABOUT_SUCCESS',
    CLIENT_LOAD_NOTES_ABOUT_FAILED: 'CLIENT_LOAD_NOTES_ABOUT_FAILED',
};

export {
    ACTIONS
};
