const ACTIONS = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',

    CLIENTS_LOAD_ALL: 'CLIENTS_LOAD_ALL',
    CLIENTS_LOAD_ALL_SUCCESS: 'CLIENTS_LOAD_ALL_SUCCESS',
    CLIENTS_LOAD_ALL_FAILED: 'CLIENTS_LOAD_ALL_FAILED',
};

export {
    ACTIONS
};
